FROM python:3.13-slim

WORKDIR /app

COPY lvl3.py .
COPY requirements.txt .
COPY utils.py .
COPY bio.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y socat && rm -rf /var/lib/apt/lists/*

EXPOSE 1010

ENV FLAG="FL1TZ{look_again;)}"

CMD ["socat","-v","-T", "90", "TCP-LISTEN:1010,fork,reuseaddr,bind=0.0.0.0", "EXEC:'python3 lvl3.py'"]
